2020-04-26 15:24:58,341 - D:/51/python/project/test/logger/logger1.py[line:38] - ERROR: error
2020-04-26 15:29:46,582 - D:/51/python/project/test/logger/logger1.py[line:38] - ERROR: error213123123
2020-04-26 15:31:31,974 - logger1.py[line:39] - ERROR: error213123123
