2019-12-26 11:19:49,758 - D:/51/python/project/test/logger/logger1.py[line:38] - ERROR: error
