2021-03-11 16:22:48,924 - D:\51\python\project\PO\LogPO.py[line:45] - DEBUG: debug
2021-03-11 16:22:48,924 - D:\51\python\project\PO\LogPO.py[line:46] - INFO: info
2021-03-11 16:22:48,924 - D:\51\python\project\PO\LogPO.py[line:47] - WARNING: 警告
2021-03-11 16:22:48,924 - D:\51\python\project\PO\LogPO.py[line:48] - ERROR: 报错
2021-03-11 16:22:48,924 - D:\51\python\project\PO\LogPO.py[line:49] - CRITICAL: 严重
2021-03-11 16:23:04,839 - D:\51\python\project\PO\LogPO.py[line:45] - DEBUG: debug
2021-03-11 16:23:04,839 - D:\51\python\project\PO\LogPO.py[line:46] - INFO: info
2021-03-11 16:23:04,839 - D:\51\python\project\PO\LogPO.py[line:47] - WARNING: 警告
2021-03-11 16:23:04,924 - D:\51\python\project\PO\LogPO.py[line:48] - ERROR: 报错
2021-03-11 16:23:04,924 - D:\51\python\project\PO\LogPO.py[line:49] - CRITICAL: 严重
