<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>测试报告</title>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/animate.css/3.5.2/animate.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/chosen/1.8.2/chosen.css" rel="stylesheet">
    <link href="../js/template12.css" rel="stylesheet">


</head>

<body class="gray-bg">
<div class="row  border-bottom white-bg dashboard-header">
    <div class="col-sm-12 text-center">
        <span style="color: #1ab394; font-size: 20px; font-weight: 700"><h1> <span id="projectName"></span></h1></span>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>报告汇总</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>


                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-12 b-r" >
                            <form class="">

                            <div class="form-row">
                                <div class="form-group col-md-3">
                                <label for="exampleFormControlInput1">需求文档</label>
                                    <span class="form-control" id="iDoc" disabled="disabled"></span>
                                </div>

                                <div class="form-group col-md-3">
                                <label for="exampleFormControlInput1">当前环境</label>
                                    <span class="form-control" id="iEnv" disabled="disabled"></span>
                                </div>

                                <div class="form-group col-md-3">
                                <label for="exampleFormControlInput1">数据库</label>
                                    <span class="form-control" id="iDatabase" disabled="disabled"></span>
                                </div>

                                <div class="form-group col-md-3">
                                <label for="exampleFormControlInput1">消耗总时间</label>
                                <span class="form-control" id="totalTime" disabled="disabled"></span>
                                </div>

                                <div class="form-group col-md-3">
                                <label for="exampleFormControlInput1">用例总数</label>
                                <span class="form-control" id="testAll" disabled="disabled"></span>
                                </div>

                                 <div class="form-group col-md-3">
                                 <label class="text-navy">成功</label>
                                 <span class="form-control" id="testPass" disabled="disabled"></span>
                                 </div>

                                 <div class="form-group col-md-3">
                                 <label class="text-danger">失败</label>
                                 <span class="form-control" id="testFail" disabled="disabled"></span>
                                 </div>

                                 <div class="form-group col-md-3">
                                 <label>跳过</label>
                                 <span class="form-control" id="testSkip" disabled="disabled"></span>
                                 </div>
                            </div>


                            </form>

                        </div>

                        <div class="col-sm-6"></div>

                        <div class="row">

                        <div class="col-sm-12">
                            <div class="col-sm-6">
                                <div style="height:350px" id="echarts-map-chart"></div>
                            </div>
                            <div class="col-sm-6">
                                <div id="container" style="width:850px;height:500px;margin:0 auto"></div>
                            </div>
                        </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>详细数据</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="input-group panel-heading" style="width: 100%; background-color: #C6C386; margin-bottom: 10px; text-align: left; font-family: Consolas;">
                        <label style="color: snow">担当者:</label>
                        <select class="chosen-select form-control" data-placeholder="----------" style="width: 200px;" name="filterClass" id="filterClass">
                            <option value="">所有</option>
                        </select>

                        <label style="color: snow">&nbsp类型:</label>
                        <select class="chosen-select form-control" data-placeholder="----------" style="width: 200px;" name="filterType" id="filterType">
                            <option value="">所有</option>
                        </select>

                        <label style="color: snow">&nbsp模块:</label>
                        <select class="chosen-select form-control" data-placeholder="----------" style="width: 200px;" name="filterSort" id="filterSort">
                            <option value="">所有</option>
                        </select>

                        <label style="color: snow"> &nbsp结果:</label>
                        <select class="chosen-select form-control" data-placeholder="----------" style="width: 200px;" name="filterResult" id="filterResult">
                            <option value="">所有</option>
                        </select>
                        <div style="float: right">
                            <label class="form-control">
                                <span class="text-navy">用例数: </span><span class="text-navy b-r" id="filterAll"></span><span> | </span>
                                <span style="color: green">成功: </span><span style="color: green" id="filterOk"></span><span> | </span>
                                <span class="text-danger">失败: </span><span class="text-danger" id="filterFail"></span><span> | </span>
                                <span class="text-warning">跳过: </span><span class="text-warning" id="filterSkip"></span>
                            </label>
                        </div>
                    </div>
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>用例编号</th><th>担当者</th><th>类型</th><th>模块</th><th>用例名称</th><th>测试日期</th><th>耗时</th><th>结果</th><th>操作</th>
                        </tr>
                        </thead>
                        <tbody id="detailBody">
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="../js/jquery.js"></script>
<script type="text/javascript" src="../js/highcharts.js"></script>
<script type="text/javascript" src="../js/exporting.js"></script>


<script src="https://cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://cdn.bootcss.com/echarts/3.8.5/echarts.min.js"></script>
<script src="https://cdn.bootcss.com/chosen/1.8.2/chosen.jquery.js"></script>



<script type="text/javascript">
	function $childNode(o) {
	    return window.frames[o]
	}
	function animationHover(o, e) {
	    o = $(o), o.hover(function () {
	        o.addClass("animated " + e)
	    }, function () {
	        window.setTimeout(function () {
	            o.removeClass("animated " + e)
	        }, 2e3)
	    })
	}
	function WinMove() {
	    var o = "[class*=col]", e = ".ibox-title", i = "[class*=col]";
	    $(o).sortable({
	        handle: e,
	        connectWith: i,
	        tolerance: "pointer",
	        forcePlaceholderSize: !0,
	        opacity: .8
	    }).disableSelection()
	}
	var $parentNode = window.parent.document;
	if ($(".tooltip-demo").tooltip({
	        selector: "[data-toggle=tooltip]",
	        container: "body"
	    }), $(".modal").appendTo("body"), $("[data-toggle=popover]").popover(), $(".collapse-link").click(function () {
	        var o = $(this).closest("div.ibox"), e = $(this).find("i"), i = o.find("div.ibox-content");
	        i.slideToggle(200), e.toggleClass("fa-chevron-up").toggleClass("fa-chevron-down"), o.toggleClass("").toggleClass("border-bottom"), setTimeout(function () {
	            o.resize(), o.find("[id^=map-]").resize()
	        }, 50)
	    }), $(".close-link").click(function () {
	        var o = $(this).closest("div.ibox");
	        o.remove()
	    }), top == this) {
	}
</script>
<script type="text/javascript">
    var resultData = {
    "testPass": 0,
    "testResult": [
        {
            "excelNo": "2",
            "className": "金浩",
            "testType": "正常",
            "testSort": "公钥加密接口",
            "description": "加密用户名",
            "testDate": "2021-12-06",
            "spendTime": "0.0327 秒",
            "status": "失败",
            "log": [
                "\n【sql语句】：org_id = select org_id from sys_user where user_no=\"jinhao\"\n\n【请求地址】：http://192.168.0.243:8001/auth/publicEncrypt?info=jinhao\n\n【参数】：{}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":\"juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==\"}</font>\n\n【当前变量】：{'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success'}\n\n<font color='purple'>【全局变量】：{'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC427040>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "3",
            "className": "金浩",
            "testType": "正常",
            "testSort": "公钥加密接口",
            "description": "加密密码",
            "testDate": "2021-12-06",
            "spendTime": "0.0241 秒",
            "status": "失败",
            "log": [
                "\n【sql语句】：zjCenterId = select zj_center_id from sys_user where user_no=\"jinhao\"\n\n【请求地址】：http://192.168.0.243:8001/auth/publicEncrypt?info=Jinhao!123\n\n【参数】：{}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":\"NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==\"}</font>\n\n【当前变量】：{'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ=='}\n\n<font color='purple'>【全局变量】：{'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6'}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC441F80>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "4",
            "className": "金浩",
            "testType": "正常",
            "testSort": "公钥加密接口",
            "description": "加密密码",
            "testDate": "2021-12-06",
            "spendTime": "0.024 秒",
            "status": "失败",
            "log": [
                "\n【sql语句】：zjCenterId = select zj_center_id from sys_user where user_no=\"jinhao\"\n\n【请求地址】：http://192.168.0.243:8001/auth/publicEncrypt?info=Jinhao!123\n\n【参数】：{}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":\"wx20yrVuqX5ucTJG8mNJ6nXKIFYzWZ+Tq4AizWm4RUVvCDdly/niq7cuzojQHvpMjpbnFpBNI2en6zOlBobwdwINFW/k6y3M/yOKC8b4qcrBUVywhDEzoTtDuW8EntzL628QYT1jGxLT1MhYy0PaPVC7wvrF0VJbAR/pJ+U2RQjJjNYIfrcLzA3IsHjOu+5gDjJZ7ZNfriMHe/cORbyEHTUgkGp+rtGvjQowDpI1CNAOmWrQtCZeqVWIX6bIfMPNC7UOtaY0oUjf/iDNRQf2HdhcgT/AdXbQ7/qY+rLni0ijmWD862j7kJuT4Z9pmKrYi9TEcMgnvSP+utykHqcpPA==\"}</font>\n\n【当前变量】：{'password': 'wx20yrVuqX5ucTJG8mNJ6nXKIFYzWZ+Tq4AizWm4RUVvCDdly/niq7cuzojQHvpMjpbnFpBNI2en6zOlBobwdwINFW/k6y3M/yOKC8b4qcrBUVywhDEzoTtDuW8EntzL628QYT1jGxLT1MhYy0PaPVC7wvrF0VJbAR/pJ+U2RQjJjNYIfrcLzA3IsHjOu+5gDjJZ7ZNfriMHe/cORbyEHTUgkGp+rtGvjQowDpI1CNAOmWrQtCZeqVWIX6bIfMPNC7UOtaY0oUjf/iDNRQf2HdhcgT/AdXbQ7/qY+rLni0ijmWD862j7kJuT4Z9pmKrYi9TEcMgnvSP+utykHqcpPA=='}\n\n<font color='purple'>【全局变量】：{'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6'}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC3AAD00>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "5",
            "className": "金浩",
            "testType": "正常",
            "testSort": "公钥加密接口",
            "description": "加密密码",
            "testDate": "2021-12-06",
            "spendTime": "0.0244 秒",
            "status": "失败",
            "log": [
                "\n【sql语句】：zjCenterId = select zj_center_id from sys_user where user_no=\"jinhao\"\n\n【请求地址】：http://192.168.0.243:8001/auth/publicEncrypt?info=Jinhao!123\n\n【参数】：{}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":\"wjIJ9Zdt80v3BrBUBlcAY08ebwLUFAoFM7LxE0VC9SIOEZJmQc0B8OPuiO2UX8KrC+wsGtVWtNS3sXmaqsRlIaZTliGn7tK/qg9WXZBFAQqomufSw6qpdPO2dgTOcEyBShZRE7QvAw4GX1XzSBoO9lru0QkT9SgNz4mltfnyv/q1tToJdZInGnAHnQXZzbhxKkYoXgnCQPPvJT3138FLl+ci6w4PoaNN++qWzcLF/dG6ck5XUVXPF6ByqyNv4pD7EE9jT/xytzv8gkuty3Vxru82cupDj4O0cq96vJm1A/xLMk/S//JmlkQ2Uezxmh2OCzMpqiZQhpndrpwcipJ9JQ==\"}</font>\n\n【当前变量】：{'password': 'wjIJ9Zdt80v3BrBUBlcAY08ebwLUFAoFM7LxE0VC9SIOEZJmQc0B8OPuiO2UX8KrC+wsGtVWtNS3sXmaqsRlIaZTliGn7tK/qg9WXZBFAQqomufSw6qpdPO2dgTOcEyBShZRE7QvAw4GX1XzSBoO9lru0QkT9SgNz4mltfnyv/q1tToJdZInGnAHnQXZzbhxKkYoXgnCQPPvJT3138FLl+ci6w4PoaNN++qWzcLF/dG6ck5XUVXPF6ByqyNv4pD7EE9jT/xytzv8gkuty3Vxru82cupDj4O0cq96vJm1A/xLMk/S//JmlkQ2Uezxmh2OCzMpqiZQhpndrpwcipJ9JQ=='}\n\n<font color='purple'>【全局变量】：{'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6'}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC4272C0>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "6",
            "className": "金浩",
            "testType": "正常",
            "testSort": "公钥加密接口",
            "description": "加密密码",
            "testDate": "2021-12-06",
            "spendTime": "0.0224 秒",
            "status": "失败",
            "log": [
                "\n【sql语句】：zjCenterId = select zj_center_id from sys_user where user_no=\"jinhao\"\n\n【请求地址】：http://192.168.0.243:8001/auth/publicEncrypt?info=Jinhao!123\n\n【参数】：{}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":\"t/xa/T1W3X9PhOw9tqtXEXPXl90q7A7AulJT+S536P5amFquCoykE37bNDWYWUpYEeo8qKwFn2NINpmLn1aKt7UDkHUogM4Y6ubyxhptyvXuyd2fIg0TJ41iGeoWfSZIHmmCN7Kkah3hbHsuQNbED4M0qYk3Fe7q9bkJJ07AhfHEw8XSkqQg+Zwd9ZsDvzDPHXFg5IIE2R1nSTdPucVJYE0CuwXeJZvVvGw3+NYhqFwPJIW68L3AXXtSHB2HOB+Q6paSVl8aTyFxllXLOnzqTlX4Vh6NU1ty0wn4oRx8Oj/rSL/kSXLhJr2xwe5MMD8ieLml8jW/FPtc2eHcAo2mTg==\"}</font>\n\n【当前变量】：{'password': 't/xa/T1W3X9PhOw9tqtXEXPXl90q7A7AulJT+S536P5amFquCoykE37bNDWYWUpYEeo8qKwFn2NINpmLn1aKt7UDkHUogM4Y6ubyxhptyvXuyd2fIg0TJ41iGeoWfSZIHmmCN7Kkah3hbHsuQNbED4M0qYk3Fe7q9bkJJ07AhfHEw8XSkqQg+Zwd9ZsDvzDPHXFg5IIE2R1nSTdPucVJYE0CuwXeJZvVvGw3+NYhqFwPJIW68L3AXXtSHB2HOB+Q6paSVl8aTyFxllXLOnzqTlX4Vh6NU1ty0wn4oRx8Oj/rSL/kSXLhJr2xwe5MMD8ieLml8jW/FPtc2eHcAo2mTg=='}\n\n<font color='purple'>【全局变量】：{'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6'}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC36E280>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "7",
            "className": "金浩",
            "testType": "正常",
            "testSort": "公钥加密接口",
            "description": "加密密码",
            "testDate": "2021-12-06",
            "spendTime": "0.0224 秒",
            "status": "失败",
            "log": [
                "\n【sql语句】：zjCenterId = select zj_center_id from sys_user where user_no=\"jinhao\"\n\n【请求地址】：http://192.168.0.243:8001/auth/publicEncrypt?info=Jinhao!123\n\n【参数】：{}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":\"jIpcb3Fkh9rqxjBtx335IPUC68OujuPkETgbFLhyjjosGC85rb2+SDajqq5sfAgjWCltGzKiqqqFNEBgEzBD+ER/q5jLzrTcSFZbPns+Dgw3tMPuL/bMrXpPF+NaURHRS4peimmMnEpx4GPr2WcZ2LNpxFCnFHbwhuO1Mgb18mSib0cFBMCapcuHF86QFypsDORZ2cwdLzz74Ln7uIBG79/ZPDBegUv4DtmpA6Tks1+gGDxo4d46FQO1BHBZpUE/mJFelL9Dph2kPJdb0Ad3S5Znz3ESVhN5xBDb1MaEi+tyXssRYlwqd0cF6FD5qMA5rpsrPRnnoLz6f9S01y1Tqg==\"}</font>\n\n【当前变量】：{'password': 'jIpcb3Fkh9rqxjBtx335IPUC68OujuPkETgbFLhyjjosGC85rb2+SDajqq5sfAgjWCltGzKiqqqFNEBgEzBD+ER/q5jLzrTcSFZbPns+Dgw3tMPuL/bMrXpPF+NaURHRS4peimmMnEpx4GPr2WcZ2LNpxFCnFHbwhuO1Mgb18mSib0cFBMCapcuHF86QFypsDORZ2cwdLzz74Ln7uIBG79/ZPDBegUv4DtmpA6Tks1+gGDxo4d46FQO1BHBZpUE/mJFelL9Dph2kPJdb0Ad3S5Znz3ESVhN5xBDb1MaEi+tyXssRYlwqd0cF6FD5qMA5rpsrPRnnoLz6f9S01y1Tqg=='}\n\n<font color='purple'>【全局变量】：{'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6'}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC40F700>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "8",
            "className": "金浩",
            "testType": "正常",
            "testSort": "公钥加密接口",
            "description": "加密密码",
            "testDate": "2021-12-06",
            "spendTime": "0.0248 秒",
            "status": "失败",
            "log": [
                "\n【sql语句】：zjCenterId = select zj_center_id from sys_user where user_no=\"jinhao\"\n\n【请求地址】：http://192.168.0.243:8001/auth/publicEncrypt?info=Jinhao!123\n\n【参数】：{}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":\"a/f//hINkhaTquQfShrYNvEsJPsF3/Um2jyWadIwYRConxTEyzuRvqHgcahBx4QQSN5ub/kdFVBWDkGUoxhBtKdHArM1ROerPMiK+HxNfpY2hF3cniPXeeJ4u55R0u72D909pe6m90ItuK+6YTCu3Pw5HEwIST5ylrYAXHfd2He+uFuIMNtbYM3umGfM1B4myp4eLHFXtQvKL1Z0XiWfgfqbLS4SPoc64mKtYjvIW43WRE1VWrl1ruYSaqF7MY51ZyEjNZlhQxQ71WtgW8Z2LjoBNsONmwo/HUgrTFps0p45YTslTfO0jon7YjsHgyfoCipNYnojO5S9M9aSg3PFXw==\"}</font>\n\n【当前变量】：{'password': 'a/f//hINkhaTquQfShrYNvEsJPsF3/Um2jyWadIwYRConxTEyzuRvqHgcahBx4QQSN5ub/kdFVBWDkGUoxhBtKdHArM1ROerPMiK+HxNfpY2hF3cniPXeeJ4u55R0u72D909pe6m90ItuK+6YTCu3Pw5HEwIST5ylrYAXHfd2He+uFuIMNtbYM3umGfM1B4myp4eLHFXtQvKL1Z0XiWfgfqbLS4SPoc64mKtYjvIW43WRE1VWrl1ruYSaqF7MY51ZyEjNZlhQxQ71WtgW8Z2LjoBNsONmwo/HUgrTFps0p45YTslTfO0jon7YjsHgyfoCipNYnojO5S9M9aSg3PFXw=='}\n\n<font color='purple'>【全局变量】：{'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6'}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC453B40>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "9",
            "className": "金浩",
            "testType": "正常",
            "testSort": "公钥加密接口",
            "description": "加密密码",
            "testDate": "2021-12-06",
            "spendTime": "0.0221 秒",
            "status": "失败",
            "log": [
                "\n【sql语句】：zjCenterId = select zj_center_id from sys_user where user_no=\"jinhao\"\n\n【请求地址】：http://192.168.0.243:8001/auth/publicEncrypt?info=Jinhao!123\n\n【参数】：{}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":\"cwRri1LHMacD7DZ0SrkrzUfh6UBHMbM3KZEl4xRKvc89GpHjk/MjCu1erM5spmMx7fibWmLzB9ILczwtkEKA2lT/EeKCOpBFgOflhp+vT6YJWHzLHFLGVMcJ9Blf2GfaaByJXGaS4vgDUv1ZQd361nlekJFzkpPYuz7hsS3x+ywxD7ex0MuLKpgzspnmoSmnYzovtUAqmmkO1epat/2YzMFii1IqMVOv9VNENJIXs5k1Opqy1cXZNO/68ccEkrTAcBSuK+fP8SVXUPY+2eFSz6Vy2F6oeXQjH4YzvA0ZU13aBIFXo6xb3sz45Nym1kmUbIKfnI/vJdxumvjf/LnCBA==\"}</font>\n\n【当前变量】：{'password': 'cwRri1LHMacD7DZ0SrkrzUfh6UBHMbM3KZEl4xRKvc89GpHjk/MjCu1erM5spmMx7fibWmLzB9ILczwtkEKA2lT/EeKCOpBFgOflhp+vT6YJWHzLHFLGVMcJ9Blf2GfaaByJXGaS4vgDUv1ZQd361nlekJFzkpPYuz7hsS3x+ywxD7ex0MuLKpgzspnmoSmnYzovtUAqmmkO1epat/2YzMFii1IqMVOv9VNENJIXs5k1Opqy1cXZNO/68ccEkrTAcBSuK+fP8SVXUPY+2eFSz6Vy2F6oeXQjH4YzvA0ZU13aBIFXo6xb3sz45Nym1kmUbIKfnI/vJdxumvjf/LnCBA=='}\n\n<font color='purple'>【全局变量】：{'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6'}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC36EC40>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "10",
            "className": "金浩",
            "testType": "正常",
            "testSort": "公钥加密接口",
            "description": "加密密码",
            "testDate": "2021-12-06",
            "spendTime": "0.0451 秒",
            "status": "失败",
            "log": [
                "\n【sql语句】：zjCenterId = select zj_center_id from sys_user where user_no=\"jinhao\"\n\n【请求地址】：http://192.168.0.243:8001/auth/publicEncrypt?info=Jinhao!123\n\n【参数】：{}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":\"Uq8TL3rahG6rpR5h66M3MNUBENjx5CFI+wYZ+NleEimWow1GZl83XDvpREmyMOXjmhepC2tvb66ffA4Br9gSNoAElGvj0SxXpUTJazugQxPhvsBdgdatdcE2/ZKyhukCSh7GHdsqprDzLtHofT7IQ/7e6/jvgC0szrhHNkYoZPXGLP0sTtUnqpeWUPCHK7F9g94O2abziBlokMjGPh013Z2tpa8kdRK7O7r+3zLoQvwW2lmrq+/QjXMOQiP+k1awjW0r3otAFdZIvlkmkfXDLJn6unRyWHplPa4cppFZbNGv+hVMxJ8AyyZA3vVaXzbcKuZpZHmqENhQmnPtDShH0w==\"}</font>\n\n【当前变量】：{'password': 'Uq8TL3rahG6rpR5h66M3MNUBENjx5CFI+wYZ+NleEimWow1GZl83XDvpREmyMOXjmhepC2tvb66ffA4Br9gSNoAElGvj0SxXpUTJazugQxPhvsBdgdatdcE2/ZKyhukCSh7GHdsqprDzLtHofT7IQ/7e6/jvgC0szrhHNkYoZPXGLP0sTtUnqpeWUPCHK7F9g94O2abziBlokMjGPh013Z2tpa8kdRK7O7r+3zLoQvwW2lmrq+/QjXMOQiP+k1awjW0r3otAFdZIvlkmkfXDLJn6unRyWHplPa4cppFZbNGv+hVMxJ8AyyZA3vVaXzbcKuZpZHmqENhQmnPtDShH0w=='}\n\n<font color='purple'>【全局变量】：{'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6'}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC404580>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "11",
            "className": "金浩",
            "testType": "正常",
            "testSort": "公钥加密接口",
            "description": "加密密码",
            "testDate": "2021-12-06",
            "spendTime": "0.023 秒",
            "status": "失败",
            "log": [
                "\n【sql语句】：zjCenterId = select zj_center_id from sys_user where user_no=\"jinhao\"\n\n【请求地址】：http://192.168.0.243:8001/auth/publicEncrypt?info=Jinhao!123\n\n【参数】：{}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":\"o51sweHV3qWBCHbswW4VMplgXUsAfBWHtQGsIx27cYNrzWYCY/FkvsinWTX2FfGOdeO/Qui7A9GwUEPSjkMy/kmBzhXp2uH+xqpp+x8jdervAWbctE5besOCr7FFT5V2R5g8R9g7K298hdfvP1vaHaFg3spjn9A7hm5cj0U9LN+NizEoK51iYsKHRdepQat9BgR7HBhiLj7YTzgHi9gFT6BdiN2c5NjSqac6NpfOdyG6BEc1uB/gcXhcr/GMB/BV7n7Muh1vdWsxZwuwyMX/0Hx/C2PIqXjob3NdQPrNCkNTtE0Hl4lVq4Y0EmmXehj9h47mr3QfiJL557Sngzg/lA==\"}</font>\n\n【当前变量】：{'password': 'o51sweHV3qWBCHbswW4VMplgXUsAfBWHtQGsIx27cYNrzWYCY/FkvsinWTX2FfGOdeO/Qui7A9GwUEPSjkMy/kmBzhXp2uH+xqpp+x8jdervAWbctE5besOCr7FFT5V2R5g8R9g7K298hdfvP1vaHaFg3spjn9A7hm5cj0U9LN+NizEoK51iYsKHRdepQat9BgR7HBhiLj7YTzgHi9gFT6BdiN2c5NjSqac6NpfOdyG6BEc1uB/gcXhcr/GMB/BV7n7Muh1vdWsxZwuwyMX/0Hx/C2PIqXjob3NdQPrNCkNTtE0Hl4lVq4Y0EmmXehj9h47mr3QfiJL557Sngzg/lA=='}\n\n<font color='purple'>【全局变量】：{'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6'}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC3AE8C0>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "12",
            "className": "金浩",
            "testType": "异常",
            "testSort": "登录",
            "description": "用户登录",
            "testDate": "2021-12-06",
            "spendTime": "0.0989 秒",
            "status": "失败",
            "log": [
                "\n【请求地址】：http://192.168.0.243:8001/auth/login\n\n【参数】：{'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ=='}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":{\"token\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2NiIsImlhdCI6MTYzODc2MzE2NywiZXhwIjoxNjM5MzY3OTY3fQ.UVHSE0PqiQk8YLhXbeRNjKbH09heZwrCm6NUm3UP6Hh5cfG-RMj9KPmxRGXeIv7AfY9qgNmQBGCvfjqFxW_z8Q\",\"expire\":86400}}</font>\n\n【当前变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9}\n\n<font color='purple'>【全局变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9, 'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6'}</font>\n\n<font color='green'>【检查返回值】：$.code:200,$.msg:{{tt}} </font>\n<traceback object at 0x000002A1FC40FD80>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 210, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "13",
            "className": "金浩",
            "testType": "正常",
            "testSort": "web端涉疫人员自行上报",
            "description": "web端涉疫人员自行上报获取二维码图片地址",
            "testDate": "2021-12-06",
            "spendTime": "0.0555 秒",
            "status": "失败",
            "log": [
                "\n【sql语句1】：xx0 = select COUNT(*) FROM ep_resident_user\n\n【sql语句2】：xx1 = select count(*) from ep_resident_user where org_id=37\n\n【请求地址】：http://192.168.0.243:8001/webReport/getQcCodeUrl/34\n\n【方法】：get\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":\"/uploadFile/QR/null网格中心数据code.jpg\"}</font>\n\n【当前变量】：None\n\n<font color='purple'>【全局变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9, 'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6', 'xx0': 398, 'xx1': 323}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC3AE800>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "14",
            "className": "金浩",
            "testType": "正常",
            "testSort": "疫情防控平台",
            "description": "涉疫人员管理-列表",
            "testDate": "2021-12-06",
            "spendTime": "0.022 秒",
            "status": "失败",
            "log": [
                "\n【请求地址】：http://192.168.0.243:8001/residentManage/getResidentList\n\n【参数】：{\n \"circulationStatus\": \"\",\n \"currPage\": 0,\n \"dataSources\": \"\",\n \"endTimeClaim\": \"\",\n \"endTimePm\": \"\",\n \"idCardNo\": \"\",\n \"name\": \"\",\n \"orgIds\": [],\n \"pageSize\": 1,\n \"startTimeClaim\": \"\",\n \"startTimePm\": \"\",\n \"type\": \"\"\n}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":{\"totalCount\":398,\"pageSize\":1,\"totalPage\":398,\"currPage\":1,\"list\":[{\"id\":46,\"name\":\"1\",\"sex\":\"男\",\"phone\":\"13013245678\",\"idCardNo\":\"123123199611280036\",\"nativePlace\":\"吉林省长春市南关区\",\"residentialAddress\":\"1\",\"workUnit\":\"1\",\"provenanceAddress\":\"黑龙江省哈尔滨市道里区\",\"riskGrade\":\"低风险\",\"transportation\":\"自驾\",\"departureTime\":\"2025-11-26 00:00:00\",\"arrivalTime\":\"2025-11-28 00:00:00\",\"controls\":\"集中隔离\",\"mpCount\":1,\"inStatus\":\"1\",\"circulationStatus\":\"监测中\",\"dataSources\":\"自行上报\",\"notes\":\"1\",\"orgId\":35,\"orgNo\":null,\"orgName\":\"网络中心2\",\"leaderName\":\"白总\",\"leaderPhone\":\"13111254522\",\"policeName\":\"红警官\",\"policePhone\":\"58454566\",\"doctorName\":\"你好\",\"doctorPhone\":\"13816102544\",\"volunteerName\":\"旅团\",\"volunteerPhone\":\"13616151211\"}]}}</font>\n\n【当前变量】：None\n\n<font color='purple'>【全局变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9, 'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6', 'xx0': 398, 'xx1': 323}</font>\n\n<font color='green'>【检查返回值】：$.code:200,$.data.totalCount:{{xx0}} </font>\n<traceback object at 0x000002A1FC3A6840>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 210, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "16",
            "className": "金浩",
            "testType": "正常",
            "testSort": "注册管理",
            "description": "网络中心注册-根据ID获取单个实体模型",
            "testDate": "2021-12-06",
            "spendTime": "0.0181 秒",
            "status": "失败",
            "log": [
                "\n【请求地址】：http://192.168.0.243:8001/register/getOrgVoById/34\n\n【参数】：None\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":{\"id\":34,\"name\":\"静安网格中心\",\"orgno\":null,\"description\":\"令狐冲刺\",\"leaderName\":\"\",\"leaderPhone\":\"\",\"policeName\":\"\",\"policePhone\":\"\",\"doctorName\":\"\",\"doctorPhone\":\"\",\"volunteerName\":\"\",\"volunteerPhone\":\"\",\"zjCenterId\":6}}</font>\n\n【当前变量】：None\n\n<font color='purple'>【全局变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9, 'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6', 'xx0': 398, 'xx1': 323}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC4270C0>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "17",
            "className": "金浩",
            "testType": "正常",
            "testSort": "注册管理",
            "description": "网络中心注册-列表",
            "testDate": "2021-12-06",
            "spendTime": "0.018 秒",
            "status": "失败",
            "log": [
                "\n【请求地址】：http://192.168.0.243:8001/register/querySysOrgPageList/34\n\n【参数】：None\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":[{\"id\":6,\"name\":\"政监中心1\",\"sysOrgVoList\":[{\"id\":34,\"name\":\"静安网格中心\"}]}]}</font>\n\n【当前变量】：None\n\n<font color='purple'>【全局变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9, 'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6', 'xx0': 398, 'xx1': 323}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC3749C0>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "18",
            "className": "金浩",
            "testType": "正常",
            "testSort": "注册管理",
            "description": "政监中心注册-根据ID获取单个实体模型",
            "testDate": "2021-12-06",
            "spendTime": "0.0206 秒",
            "status": "失败",
            "log": [
                "\n【请求地址】：http://192.168.0.243:8001/register/getZjCenterById/7\n\n【参数】：None\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":{\"id\":7,\"name\":\"政监中心2\",\"code\":\"ZJ0011637025722399\",\"responsiblePerson\":\"dc\",\"address\":\"上海\",\"area\":\"静安\",\"contactPerson\":\"dc\",\"contactPhone\":\"123\",\"status\":1,\"createTime\":\"2021-11-16 01:22:02\",\"updateTime\":\"2021-11-16 10:17:21\"}}</font>\n\n【当前变量】：None\n\n<font color='purple'>【全局变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9, 'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6', 'xx0': 398, 'xx1': 323}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC404200>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "22",
            "className": "金浩",
            "testType": "正常",
            "testSort": "注册管理",
            "description": "政监中心注册-启用1/停用2",
            "testDate": "2021-12-06",
            "spendTime": "0.0277 秒",
            "status": "失败",
            "log": [
                "\n【请求地址】：http://192.168.0.243:8001/register/updateStatusById/9\n\n【参数】：None\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":{\"id\":9,\"name\":\"政监中心4\",\"code\":\"ZJ0011637026003673\",\"responsiblePerson\":\"dc\",\"address\":\"上海市\",\"area\":\"普陀\",\"contactPerson\":\"dc\",\"contactPhone\":\"23124\",\"status\":1,\"createTime\":\"2021-11-16 01:26:44\",\"updateTime\":\"2021-12-06 11:59:27\"}}</font>\n\n【当前变量】：None\n\n<font color='purple'>【全局变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9, 'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6', 'xx0': 398, 'xx1': 323}</font>\n\n<font color='green'>【检查返回值】：$.code:200,$.data.area:普陀 </font>\n<traceback object at 0x000002A1FC4042C0>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 210, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "24",
            "className": "金浩",
            "testType": "正常",
            "testSort": "注册管理",
            "description": "网格中心注册-更新",
            "testDate": "2021-12-06",
            "spendTime": "0.0245 秒",
            "status": "失败",
            "log": [
                "\n【请求地址】：http://192.168.0.243:8001/register/updateOrgVo\n\n【参数】：{\n \"description\": \"令狐冲刺\",\n \"doctorName\": \"\",\n \"doctorPhone\": \"\",\n \"id\": 34,\n \"leaderName\": \"\",\n \"leaderPhone\": \"\",\n \"name\": \"静安网格中心\",\n \"policeName\": \"\",\n \"policePhone\": \"\",\n \"volunteerName\": \"\",\n \"volunteerPhone\": \"\",\n \"zjCenterId\": \"6\"\n}\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":{\"id\":34,\"name\":\"静安网格中心\",\"orgno\":null,\"description\":\"令狐冲刺\",\"leaderName\":\"\",\"leaderPhone\":\"\",\"policeName\":\"\",\"policePhone\":\"\",\"doctorName\":\"\",\"doctorPhone\":\"\",\"volunteerName\":\"\",\"volunteerPhone\":\"\",\"zjCenterId\":6}}</font>\n\n【当前变量】：None\n\n<font color='purple'>【全局变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9, 'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6', 'xx0': 398, 'xx1': 323}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC374A80>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "32",
            "className": "金浩",
            "testType": "正常",
            "testSort": "疫情防控平台",
            "description": "获取网格中心下拉框数据",
            "testDate": "2021-12-06",
            "spendTime": "0.0161 秒",
            "status": "失败",
            "log": [
                "\n【请求地址】：http://192.168.0.243:8001/dict/querySysOrgData\n\n【方法】：get\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":[{\"id\":-1,\"name\":\"超级管理员机构\"},{\"id\":34,\"name\":\"静安网格中心\"},{\"id\":35,\"name\":\"网络中心2\"},{\"id\":37,\"name\":\"网格中心3\"},{\"id\":38,\"name\":\"网格中心4\"},{\"id\":39,\"name\":\"网格中心7\"},{\"id\":43,\"name\":\"1\"},{\"id\":44,\"name\":\"1\"},{\"id\":45,\"name\":\"1\"}]}</font>\n\n【当前变量】：None\n\n<font color='purple'>【全局变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9, 'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6', 'xx0': 398, 'xx1': 323}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC3728C0>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "33",
            "className": "金浩",
            "testType": "正常",
            "testSort": "疫情防控平台",
            "description": "根据政监中心ID获取网格中心下拉框数据",
            "testDate": "2021-12-06",
            "spendTime": "0.0163 秒",
            "status": "失败",
            "log": [
                "\n【请求地址】：http://192.168.0.243:8001/dict/querySysOrgDataByZjCenterId/2\n\n【方法】：get\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":[]}</font>\n\n【当前变量】：None\n\n<font color='purple'>【全局变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9, 'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6', 'xx0': 398, 'xx1': 323}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC3A6840>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "35",
            "className": "金浩",
            "testType": "正常",
            "testSort": "疫情防控平台",
            "description": "获取政监中心下拉框数据",
            "testDate": "2021-12-06",
            "spendTime": "0.0157 秒",
            "status": "失败",
            "log": [
                "\n【请求地址】：http://192.168.0.243:8001/dict/queryZjCenterData\n\n【方法】：get\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":[{\"id\":-1,\"name\":\"超级管理员政监控中心\"},{\"id\":6,\"name\":\"政监中心1\"},{\"id\":7,\"name\":\"政监中心2\"},{\"id\":8,\"name\":\"政监中心3\"},{\"id\":9,\"name\":\"政监中心4\"},{\"id\":10,\"name\":\"测试\"},{\"id\":12,\"name\":\"政监中心8\"},{\"id\":13,\"name\":\"证监中心6\"}]}</font>\n\n【当前变量】：None\n\n<font color='purple'>【全局变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9, 'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6', 'xx0': 398, 'xx1': 323}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC4046C0>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        },
        {
            "excelNo": "38",
            "className": "金浩",
            "testType": "正常",
            "testSort": "鉴权中心",
            "description": "用户登出",
            "testDate": "2021-12-06",
            "spendTime": "0.0733 秒",
            "status": "失败",
            "log": [
                "\n【请求地址】：http://192.168.0.243:8001/auth/logout\n\n【参数】：None\n\n【方法】：post\n\n<font color='blue'>【返回】：{\"code\":200,\"msg\":\"success\",\"data\":\"退出成功\"}</font>\n\n【当前变量】：None\n\n<font color='purple'>【全局变量】：{'sys_org_id': '34', 'ep_zj_center_id': 9, 'password': 'NgTj5zGcgsOAwnoYQWWBDjsT1mFEiz/PH/467NiFP9fQkp3c69mpK9jMECEaqDzAI8QBKdykMI4UNvdNjNDjemEQAOk8RiJ6d6rDbYRzDXGkJVxeMpcOuZ8fdCqYobZnfdc7dggy9f++b3u+uQwAlHkw0f/oplvNYDTs2pSFFtVRXbOPeTTb7viL7snX3C1ki+S+cJM8eYB5O7aNAFx2pCHFpTxm8ga7mWWI0eKWC3HIMTwPONXR2hHY1KkJFDuXr5VfjmF32KNIfNvT63wZv6FuR1jlyneRVVBPPH+6Xfn5cksck4zSSTaxhlLyyRnyNvVPVv5gjS5GthJ4UyZOzQ==', 'userNo': 'juHGSlikbfaY1JOIu0xfemjeExILjo1z904Nh94zqRKRTmYBIxNJyHRoYI7vXmJvg0V87SRMBcT9Q+f3E8MS7Si7js5P4hQzX4E3S2NN0Rd3pdkXiVKgQV80uqOHhYi6X+5k0w8IdNgKX7wUiFwYd33CKBUMXUxB5Tnps85nlaiK65WJEMeUgFW68RTuufcr3+edEtpXSOmNb+dz37mdrN361+EM6QU9o7zOXarYA944ONDln3ZUFYcpQp46dr1YT4zHcZ9s3d1+PNke1wVfO6JoJqUMBWeFPo9gjzWt94aPmzwAsxFD4XWIe7r6+X/z72mmK9p7e67GcTWEwd41bQ==', 'tt': 'success', 'org_id': 34, 'zjCenterId': '6', 'xx0': 398, 'xx1': 323}</font>\n\n<font color='green'>【检查返回值】：$.code:200 </font>\n<traceback object at 0x000002A1FC453100>\n",
                "Traceback (most recent call last):\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 188, in result\n    self.setCaseParam(excelNo, \"OK\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n",
                "\nDuring handling of the above exception, another exception occurred:\n\n",
                "Traceback (most recent call last):\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 593, in run\n    self._callTestMethod(testMethod)\n",
                "  File \"C:\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n",
                "  File \"C:\\Python39\\lib\\site-packages\\parameterized\\parameterized.py\", line 533, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\epidemic.py\", line 31, in test5\n    xls1.result(excelNo, iType, iSort, iName, iPath, iMethod, iParam, iKey, globalVar, sql, tester, caseQty)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 214, in result\n    self.setCaseParam(excelNo, \"Fail\", d_res, sql_before, sql_after)\n",
                "  File \"D:\\51\\python\\project\\instance\\zyjk\\epidemic\\interface\\xls.py\", line 238, in setCaseParam\n    self.Openpyxl_PO.wb.save(self.varExcel)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\workbook\\workbook.py\", line 407, in save\n    save_workbook(self, filename)\n",
                "  File \"C:\\Python39\\lib\\site-packages\\openpyxl\\writer\\excel.py\", line 291, in save_workbook\n    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)\n",
                "  File \"C:\\Python39\\lib\\zipfile.py\", line 1239, in __init__\n    self.fp = io.open(file, filemode)\n",
                "PermissionError: [Errno 13] Permission denied: 'D:\\\\51\\\\python\\\\project\\\\instance\\\\zyjk\\\\epidemic\\\\interface\\\\testcase.xlsx'\n"
            ]
        }
    ],
    "iDoc": "http://192.168.0.237:8001/swagger-ui.html",
    "iEnv": "test",
    "iDatabase": "epd",
    "test": "",
    "testAll": "37",
    "testFail": 22,
    "beginTime": "2021-12-06 11:59:26",
    "totalTime": "1秒",
    "testSkip": 15,
    "projectName": "招远防疫项目接口测试报告",
    "testError": 0
};

    function clickRow(obj){
        $("#detailBody").children("tr").attr("style","font-family: Consolas");
        $(obj).attr("style","font-family: Consolas; background-color: #b0d877");
    }

    function details(obj) {
        if ($(obj).text() == '展开') {
            var len = $(obj).parent().parent().children().length;
            var detailLog = "";
            var logs = resultData["testResult"][parseInt($(obj).attr("buttonIndex"))]["log"];
            $(obj).text("收缩");
            $(obj).removeClass("btn-primary");
            $(obj).addClass("btn-danger");
            $.each(logs, function (i, n) {
                detailLog = detailLog + "<p>" + n + "</p>";
            });
            $(obj).parent().parent().after("<tr><td colspan='" + len + "'><div style='font-family: Consolas;font-size:16px;word-break:break-all'>" + detailLog + "</div></td></tr>");
        } else if ($(obj).text() == '收缩') {
            $(obj).parent().parent().next().remove();
            $(obj).text("展开");
            $(obj).removeClass("btn-danger");
            $(obj).addClass("btn-primary");
        }

    }
    $(function () {
        $("#iDoc").text(resultData["iDoc"]);
        $("#iEnv").text(resultData["iEnv"]);
        $("#iDatabase").text(resultData["iDatabase"]);
        $("#projectName").text(resultData["projectName"]);
        $("#testPass").text(resultData["testPass"]);
        $("#testFail").text(resultData["testFail"]);
        $("#testSkip").text(resultData["testSkip"]);
        $("#testAll").text(resultData["testAll"]);
        $("#beginTime").text(resultData["beginTime"]);
        $("#totalTime").text(resultData["totalTime"]);
        $("#filterAll").text(resultData["testAll"]);
        $("#filterOk").text(resultData["testPass"]);
        $("#filterFail").text(resultData["testFail"]);
        $("#filterSkip").text(resultData["testSkip"]);
        var classNames = [];
        var classTypes = [];
        var classSorts = [];
        var results = [];
        $.each(resultData["testResult"], function (i, n) {
            if (classNames.indexOf(n["className"]) == -1) {
                classNames.push(n["className"]);
            }
            if (classTypes.indexOf(n["testType"]) == -1) {
                classTypes.push(n["testType"]);
            }
            if (classSorts.indexOf(n["testSort"]) == -1) {
                classSorts.push(n["testSort"]);
            }
            if (results.indexOf(n["status"]) == -1) {
                results.push(n["status"]);
            }
        });

        $.each(classNames, function (i, n) {
            $("#filterClass").append("<option value='" + n + "' hassubinfo='true'>" + n + "</option>");
        });
        $.each(classTypes, function (i, n) {
            $("#filterType").append("<option value='" + n + "' hassubinfo='true'>" + n + "</option>");
        });
        $.each(classSorts, function (i, n) {
            $("#filterSort").append("<option value='" + n + "' hassubinfo='true'>" + n + "</option>");
        });
        $.each(results, function (i, n) {
            $("#filterResult").append("<option value='" + n + "' hassubinfo='true'>" + n + "</option>");
        });

        $("#filterClass").chosen({search_contains: true});
        $("#filterType").chosen({search_contains: true});
        $("#filterSort").chosen({search_contains: true});
        $("#filterResult").chosen({search_contains: true});

        function generateResult(className, testType, testSort, caseResult) {
            $("#detailBody").children().remove();
            var filterAll = 0;
            var filterOk = 0;
            var filterFail = 0;
            var filterSkip = 0;
            $.each(resultData["testResult"], function (i, n) {
                if ((className == "" || n["className"] == className) && (caseResult == "" || n["status"] == caseResult) && (testType == "" || n["testType"] == testType) && (testSort == "" || n["testSort"] == testSort)) {
                    filterAll += 1;
                    var status = "";
                    if (n["status"] == '成功') {
                        filterOk += 1;
                        status = "<td><span class='text-navy'>成功</span></td>";
                    } else if (n["status"] == '失败') {
                        filterFail += 1;
                        status = "<td><span class='text-danger'>失败</span></td>";
                    } else if (n["status"] == '跳过') {
                        filterSkip += 1;
                        status = "<td><span class='text-warning'>跳过</span></td>";
                    } else {
                        status = "<td><span>" + n["status"] + "</span></td>";
                    }

                    var tr = "<tr style='font-family: Consolas'>" +
                        "<td>" + n["excelNo"] + "</td>" +
                        "<td>" + n["className"] + "</td>" +
                        "<td>" + n["testType"] + "</td>" +
                        "<td>" + n["testSort"] + "</td>" +
                        "<td>" + n["description"] + "</td>" +
                        "<td>" + n["testDate"] + "</td>" +
                        "<td>" + n["spendTime"] + "</td>" +
                        status + "<td><button type='button' onclick='details(this)' buttonIndex='" + i + "' class='btn btn-primary btn-xs' style='margin-bottom: 0px'>展开</button></td></tr>"
                    $("#detailBody").append(tr);
                }
            });
            $("#filterAll").text(filterAll);
            $("#filterOk").text(filterOk);
            $("#filterFail").text(filterFail);
            $("#filterSkip").text(filterSkip);
        }

        generateResult("", "", "", "");

        $("#filterClass").on('change', function () {
            var className = $("#filterClass").val();
            var testType = $("#filterType").val();
            var testSort = $("#filterSort").val();
            var caseResult = $("#filterResult").val();
            generateResult(className, testType, testSort, caseResult);
        });

        $("#filterType").on('change', function () {
            var className = $("#filterClass").val();
            var testType = $("#filterType").val();
            var testSort = $("#filterSort").val();
            var caseResult = $("#filterResult").val();
            generateResult(className, testType, testSort, caseResult);
        });

        $("#filterSort").on('change', function () {
            var className = $("#filterClass").val();
            var testType = $("#filterType").val();
            var testSort = $("#filterSort").val();
            var caseResult = $("#filterResult").val();
            generateResult(className, testType, testSort, caseResult);
        });

        $("#filterResult").on('change', function () {
            var className = $("#filterClass").val();
            var testType = $("#filterType").val();
            var testSort = $("#filterSort").val();
            var caseResult = $("#filterResult").val();
            generateResult(className, testType, testSort, caseResult);
        });

        //$(".chosen-select").trigger("chosen:updated");

        function pie() {
            var option = {
                title: {
                    text: '测试用例运行结果',
                    subtext: '',
                    x: 'center'
                },
                tooltip: {
                    trigger: 'item',
                    formatter: "{a} <br/>{b} : {c} ({d}%)"
                },
                legend: {
                    orient: 'vertical',
                    left: 'left',
                    data: ['失败', '跳过', '成功']
                },
                series: [
                    {
                        name: '运行结果',
                        type: 'pie',
                        radius: '55%',
                        center: ['50%', '60%'],
                        data: [
                            {value: resultData["testFail"], name: '失败'},
                            {value: resultData["testSkip"], name: '跳过'},
                            {value: resultData["testPass"], name: '成功'}
                        ],
                        itemStyle: {
                            emphasis: {
                                shadowBlur: 10,
                                shadowOffsetX: 0,
                                shadowColor: 'rgba(0, 0, 0, 0.5)'
                            }
                        }
                    }
                ]
            };
            var chart = echarts.init(document.getElementById("echarts-map-chart"));
            chart.setOption(option);
        }
        pie();

    });

</script>

<script type="text/javascript">
        var sum = parseInt(resultData["testPass"]) + parseInt(resultData["testFail"]) + parseInt(resultData["testSkip"]);
        //alert(sum)
	$(function () {
    $('#container').highcharts({
        chart: {
        },
        title: {
            text: '接口测试覆盖率分布图'
        },
		//x轴
        xAxis: {
            categories: ['用例总数( ' + sum + ')','成功','失败']
        },
        tooltip: {
            formatter: function() {
                var s;
                if (this.point.name) { // the pie chart
                    s = ''+
                        this.point.name +': '+ this.y +' 个用例';
                } else {
                    s = ''+
                        this.x  +': '+ this.y;
                }
                return s;
            }
        },
        labels: {
            items: [{
                html: '执行用例饼图',
                style: {
                    left: '20px',
                    top: '8px',
                    color: 'black'
                }
            }]
        },
        series: [{
            type: 'column',
            name: '成功',
            data: [resultData["testPass"]],
            color: Highcharts.getOptions().colors[9]
        }, {
            type: 'column',
            name: '失败',
            data: [resultData["testFail"]],
            color: Highcharts.getOptions().colors[5]
        }, {
            type: 'column',
            name: '跳过',
            data: [resultData["testSkip"]],
            color: Highcharts.getOptions().colors[1]
        }, {
            type: 'pie',
            name: 'Total consumption',
            data: [{
                name: '成功',
                y: resultData["testPass"],
                color: Highcharts.getOptions().colors[9]
            }, {
                name: '失败',
                y: resultData["testFail"],
                color: Highcharts.getOptions().colors[5]
            }, {
                name: '跳过',
                y: resultData["testSkip"],
                color: Highcharts.getOptions().colors[1]
            }],
            center: [50, 80],
            size: 100,
            showInLegend: false,
            dataLabels: {
                enabled: false
            }
        }]
    });
});
</script>

</body>
</html>
